---

- name: Verify
  hosts: pystemon
  vars:
    pystemon_home: /var/_pystemon
    pystemon_virtualenv: "{{ pystemon_home }}/env-pystemon"
    pip_bin: "{{ pystemon_virtualenv }}/bin/pip"
  tasks:
    - name: Ensure /var/_pystemon/pystemon/pystemon.py file is present
      ansible.builtin.stat:
        path: /var/_pystemon/pystemon/pystemon.py
      register: py
    - name: Validate pystemon.py present
      ansible.builtin.assert:
        that: py.stat.exists and py.stat.size != 0 and py.stat.mode == '0755'

    - name: Pip freeze
      ansible.builtin.command: "{{ pip_bin }} freeze"
      changed_when: false
      register: freeze
    - name: Validate pip modules
      ansible.builtin.assert:
        that:
          - item in freeze.stdout
          - freeze.rc == 0
      with_items:
        - PyYAML
        - redis
        - requests
        - urllib

    - name: Help command
      ansible.builtin.command: /var/_pystemon/pystemon/pystemon.py -h
      changed_when: false
      register: h
    - name: Validate help command
      ansible.builtin.assert:
        that:
          - "'Usage: pystemon.py' in h.stdout"
          - h.rc == 0
